runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  PGHOST: "34.173.45.201"
  PGUSER: "postgres"
  PGPASSWORD: "Krishna@123"
  PGDATABASE: "postgres"
  INSTANCE_CONNECTION_NAME: "weatherdataacquisition:us-central1:weather-data-instance"
