runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  PGHOST: "/cloudsql/weatherdataacquisition:us-central1:YOUR_INSTANCE_NAME"
  PGUSER: "postgres"
  PGPASSWORD: "Krishna@123"
  PGDATABASE: "postgres"
